#!/bin/sh

if gcc -o $1 $1.c $2; then
	echo -----COMPILED SUCCESSFULLY-----;
	echo  ;
	if ./$1; then
		echo  ;
		echo -----         END         -----;
	else
		echo  ;
		echo -----ERROR RUNNING-----;
	fi
else
	echo -----ERROR COMPILING-----;
fi
